name: Gradle Publish

on:
  push:
    branches: ['main']

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Publish
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish
        env:
          # GitHub Packages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          tag: '1.20.1-${{ vars.GITHUB_RUN_NUMBER }}'
